import Head from 'next/head'
import { useState } from 'react'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Portfolio from '../components/Portfolio'
import Services from '../components/Services'

export default function Home() {
  const [darkMode, setDarkMode] = useState(true)
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Jauhar Muhammed Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-5 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">
          <Navbar darkMode={darkMode} setDarkMode={setDarkMode}/>
          <Hero/>
        </section>
        <Services/>
        <Portfolio/>
      </main>
    </div>
  )
}
